### PR TITLE
Taskcluster py3 update

### PR DESCRIPTION
**Pull request by hneiva**

### CODE REVIEW

**Comment by jmaher** [comment]
@bakulf this repo hasn't had commits in a long time, and the CI has been failing for a while- do you know if this is active, or can we archive secure-proxy?

**Comment by bakulf** [comment]
We are working on a next phase for this project. We should have news to share in a couple of months max

**Comment by hneiva** [comment]
@bakulf "Secure-Proxy tests" and "ci/circleci" builds are failing, are we ok to ignore these to merge?

**Comment by hneiva** [comment]
@bakulf should we close this PR? It's been almost 1 year :)
Is this extension still required?

**Pull request closed without merging**
